SOURCES=../initLB.cpp ../boundary.cpp ../collision.cpp ../streaming.cpp\
 		../computeCellValues.cpp ../helper.cpp ../DataStructure.cpp BoundaryBufferTest.cpp TESTvisual.cpp\

COMPILER=g++
MODE=-DTEST

all:
	$(COMPILER) -o BBTest $(SOURCES) $(MODE) -I../ -I./
