SOURCES=../initLB.cpp ../visualLB.cpp ../boundary.cpp ../collision.cpp ../streaming.cpp\
 		../computeCellValues.cpp ../helper.cpp ../DataStructure.cpp BoundaryBufferTest.cpp

COMPILER=g++
MODE=-DTEST

all:
	$(COMPILER) -o BBTest $(SOURCES) $(MODE) -I../
